### PR TITLE
Add notes

### PR DESCRIPTION
**Pull request by thabbott**
Added a folder for notes and notes about time stepping.

### CODE REVIEW

**Comment by RaphaelRR** [comment]
I'll have some time to do that tomorrow, if that works. Are you all ok if we start with a scheme that is not conservative to numerical precision? (no flux limiter, no WENO etc...). It will do the job just fine at first, and will be much easier to modify, and the results will be less opaque. In other words, it will be easier to develop in a first time.

**Comment by thabbott** [comment]
Shouldn't any finite-volume advection scheme conserve to numerical precision? Regardless, though, I think starting simple is the way to go, and if we design the code well it should be easy to drop in a new advection scheme at some point in the future.

**Comment by ali-ramadhan** [comment]
I can write some documentation on the need for a staggered grid and why the C-grid is the "least worst". Need to do this for Oceananigans anyways.

> Are you all ok if we start with a scheme that is not conservative to numerical precision?

I think that's a good idea! We should set easy goals. WENO in particular is not easy to implement... Agree with Tristan that I'm not sure how it wouldn't be conservative, but definitely a good idea to just start with the simplest advection scheme first.

**Comment by RaphaelRR** [comment]
Sorry, confused myself here. Yes they are all conservative. TVD schemes are just well behaved near fronts. We don't have to care about that for now if paramaterized+implicit diffusion is large enough to prevent the formation of too sharp gradients.

If the scheme is not TVD, we might start to see funny unphysical behavior when simulating things like a downdraft impacting the surface.

**Comment by RaphaelRR** [comment]
Also, just to confirm, I'll post homebrew notes on general (non limited) flux reconstruction by tomorrow.

**Pull request merged**
