### PR TITLE
n-density dry model

### LINKED ISSUE #49: Some concerns about the Klemp (2007) equation set and suggestions for transitioning to a moist model
I want to discuss what I see as a potential problem with following the Klemp (2007) paper exactly (which is where JULES.jl currently seems to be heading) as we work on converting from a dry to a moist model, which is that the way Klemp (2007) uses dry density prevents its equation set from working in a limit where the entire atmosphere is made of water. This is admittedly a pretty academic problem, but for the sake of flexibility I would rather use an equation set that doesn't break down for extremely condensible-rich atmospheres. 

My suggestions is that, moving forward, we use the Klemp (2007) paper as a useful guide but base our model a slightly different set of equations. Something like equations 24-27 and 31-32 from [Satoh (2003)](https://journals.ametsoc.org/doi/pdf/10.1175/1520-0493%282003%29131%3C1033%3ACSFACN%3E2.0.CO%3B2) (plus an appropriate thermodynamic equation) would be a more robust set of governing equations, since they still make sense even with zero dry density. The key differences from Klemp (2007) are that Satoh (2003) 
1. tracks the mass of water species as concentrations relative to total mass rather than mixing ratios relative to dry mass, and
1. defines ρu as the total mass flux, not just the flux of dry mass

One intermediate goal we could work toward that would give us a chance to start playing with equation sets with multiple massive species but without all of the complexity of moist thermodynamics would be to work on writing code that integrates a set of equations for two non-condensible ideal gases (call them *a* and *b*):

<a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\dpi{300}&space;\frac{\partial&space;\rho_a}{\partial&space;t}&space;&plus;&space;\nabla&space;\cdot&space;\left(\rho_a&space;{\bf&space;u}&space;\right&space;)&space;=&space;D_a&space;\\&space;\frac{\partial&space;\rho_b}{\partial&space;t}&space;&plus;&space;\nabla&space;\cdot&space;\left(\rho_b&space;{\bf&space;u}&space;\right&space;)&space;=&space;D_b&space;\\&space;\frac{\partial&space;\rho&space;{\bf&space;u}}{\partial&space;t}&space;&plus;&space;\nabla&space;\cdot&space;\left(\rho&space;{\bf&space;u}&space;{\bf&space;u}&space;\right&space;)&space;=&space;-\nabla&space;p&space;-&space;\rho&space;g&space;\hat{z}&space;&plus;&space;{\bf&space;F}&space;\\&space;\frac{\partial&space;\rho&space;s}{\partial&space;t}&space;&plus;&space;\nabla&space;\cdot&space;\left(\rho&space;s&space;{\bf&space;u}&space;\right&space;)&space;=&space;0&space;\;\;(???)&space;\\&space;\rho&space;=&space;\rho_a&space;&plus;&space;\rho_b&space;\\&space;p&space;=&space;p_a&space;&plus;&space;p_b&space;=&space;(\rho_a&space;R_a&space;&plus;&space;\rho_b&space;R_b)T" target="_blank"></a>

(I'm using the notation from the Satoh paper---so the *D*s are diffusive fluxes, and the **F** is viscous dissipation. I've put question marks on the RHS of the entropy equation since I need to think more about what should go there---presumably a source term corresponding the momentum sink and probably a mixing terms of the two gases aren't identical.)

This would give us a chance to check the robustness of the equation set (e.g., does everything still work with ρ_a = 0?) and play with how best to implement a model with multiple massive species in JULES, all without having to deal with a ton of complicated thermodynamic bookkeeping. If you think this sounds like a reasonable next step I can work on closing this equation set (and replacing entropy with some other thermodynamic variable, if you'd prefer) to give us something you can actually work on implementing.

### LINKED ISSUE #52: Viscosity μ (Pa·s) vs. kinematic viscosity ν (m²/s)?
Just to confirm, we want to use kinematic viscosity ν (m²/s)?

it seems that the atmospheric modeling community always means kinemtic viscosity (m²/s) when they say "viscosity".

### LINKED ISSUE #54: Worth retaining modified potential temperature as a prognostic variable?
It's convenient if you want to work with dry air + dilute water vapor but doesn't extend in a particularly straightforward way to other situations, so it's unclear to me whether it's worth keeping it in JULES (as opposed to just developing the model with entropy for now). Thoughts?

### LINKED ISSUE #55: Thermodynamic reference states need re-organizing
The way we're diagnosing temperature and pressure from entropy assumes that all massive tracers have an entropy defined with the same reference temperature, but the way that reference states are stored (one for each massive tracer) doesn't enforce that, since each massive tracer has its own reference temperature. (This is something we could address when we add support for massive tracers that aren't non-condensible ideal gases, since this will require some substantial additions to the model thermodynamics.)

### LINKED ISSUE #56: Bug in diffusion operators?
I think the diffusive fluxes in `compressible_operators.jl`:

```julia
@inline diffusive_flux_x(i, j, k, grid, κᶠᶜᶜ, ρ, C) = κᶠᶜᶜ * Axᵃᵃᶠ(i, j, k, grid) * δxᶠᵃᵃ(i, j, k, grid, C_over_ρ, C, ρ)
@inline diffusive_flux_y(i, j, k, grid, κᶜᶠᶜ, ρ, C) = κᶜᶠᶜ * Ayᵃᵃᶠ(i, j, k, grid) * δyᵃᶠᵃ(i, j, k, grid, C_over_ρ, C, ρ)
@inline diffusive_flux_z(i, j, k, grid, κᶜᶜᶠ, ρ, C) = κᶜᶜᶠ * Azᵃᵃᵃ(i, j, k, grid) * δzᵃᵃᶠ(i, j, k, grid, C_over_ρ, C, ρ)

@inline function ∂ⱼκᵢⱼ∂ᵢc(i, j, k, grid, κˣ, κʸ, κᶻ, ρᵈ, C)
    return 1/Vᵃᵃᶜ(i, j, k, grid) * (δxᶜᵃᵃ(i, j, k, grid, diffusive_flux_x, κˣ, ρᵈ, C) +
                                    δyᵃᶜᵃ(i, j, k, grid, diffusive_flux_y, κʸ, ρᵈ, C) +
                                    δzᵃᵃᶜ(i, j, k, grid, diffusive_flux_z, κᶻ, ρᵈ, C))
end
```
are missing a division by the grid spacing. (Without it the units don't work out.) This might explain when we've been finding that the verification experiments require a smaller diffusivity than is typically reported in publications.

### LINKED ISSUE #57: Update viscosity (and diffusivity?) values in verification experiments.
[Straka et al. (1993)](https://doi.org/10.1002/fld.1650170103) use a constant isotropic diffusivity of 75 m²/s for the density current test case (no word on viscosity).

Can't find the value for the dry rising thermal bubble but will update with the value when I find it.

### LINKED ISSUE #58: Account for bulk viscosity
We should probably be including the effects of the bulk viscosity in the momentum equation: the ⅓μ∇(∇⋅u) term.

See: https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_equations#Compressible_flow

Probably doesn't matter for the simpler verification tests we've carried out. Also not sure if it's included (or accounted for) with LES. Will have to investigate more.

### LINKED ISSUE #59: Abstraction for velocity fields without extra memory allocations
Right now getting velocity is a little clunky as you have to do something like

```julia
model.momenta.ρu[i, j, k] / model.density[i, j, k]
```

Would be nice to have an abstraction for velocity fields like
```julia
struct LazyVelocityField
    momentum:: Field
    density :: Field
end

getindex(A::LazyVelocityField, inds...) = A.momentum[i, j, k] / A.density[i, j, k]
```
then we can just write `model.velocities.u[i, j, k]` and it'll lazily calculate the velocity.

The powerful feature (besides zero memory allocations) is that we can pass this lazy velocity field around to operators and other functions just like a regular field.

Could also use it to tracers (instead of mass-weighted tracer densities [?] if that's fields like ρθ are called) and it could replace the use of functions like `U_over_ρ` and `C_over_ρ`.

### PR DESCRIPTION
**Pull request by thabbott**
I have an implementation of an n-density dry model that seems to be working reasonably well using energy as the prognostic thermodynamic variable ...

[Energy, one gas](https://drive.google.com/open?id=1kVxAefO7qunFf2wqGh5i0pKgeM5Y_yjg)
[Energy, three gases](https://drive.google.com/open?id=13LKNQ_PnBfFZKVo8Zqn780FbFzcpjO1D)

... but that doesn't work particularly well with entropy ...

[Entropy, one gas](https://drive.google.com/open?id=15a_rtqkOnP_hVZBUpip6ZRGLk3KeWpmI)
[Entropy, three gases](https://drive.google.com/open?id=1Rfs4gJkYY8gp0UKB6XeTSuifULdc5RxG)

I *think* the issue is representing entropy production by mixing, which is hard to compute accurately. The rate of entropy production by mixing depends non-linearly on mass mixing rates and the entropy of a specific constituent blow up at low densities, and those two things together make me suspect that it will be hard to model mass diffusion when using entropy as the thermodynamic variable without producing spurious energy/pressure/temperature sources. (It's also possible there's a bug in the code I wrote...)

I'm labeling this as work in progress (and think we should hold off on merging for now) because the code is getting a little clunky. Some additions to the code I think would be useful include:
1. a more robust approach to tracking which model tracers are the thermodynamic variable and the densities (right now the code assumes that they're at certain indices of `model.tracers`)
1. a more streamlined way to include diagnostic fields in operators. #59 would address this.
1. some way to enforce boundary conditions on diagnostic fields (e.g. pressure, diffusive fluxes). Right now this can be done indirectly by setting boundary conditions on prognostic fields, but having a more direct way to apply them would simplify the code (and let us avoid hacks like the one in `diffusive_pressure_flux_z` in `compressible_operators.jl`, which is currently there because I couldn't figure out any other way to ensure the flux was zero at the top and bottom boundaries). #59 could also address this.

@ali-ramadhan, let me know if you're interesting in working on any of these additions. (Might be worth doing some pair programming so we make sure we're both happy with the resulting code.)

It also might be worth adding some regression tests before we start working on any of the above so that we have a way of making sure we're not changing model behavior (apart from fixes to any bugs we find) while refactoring.

Resolves #49
Resolves #52
Resolves #54
Resolves #55
Resolves #56
Resolves #57
Resolves #58
Resolves #59

### CODE REVIEW

**Comment by thabbott** [comment]
Also want to note that this branch has or will have changes that address #49 (but need to update the notes from that issue), #52, #54, #55, #56, #57, #58, and #59.

**Comment by ali-ramadhan** [comment]
Pretty epic PR! Super cool to see the three gas thermal bubble and the difference between energy and entropy.

For entropy, I'm not familiar with the spurious mixing issue but it seems really bad with the three gas thermal bubble. Even with the single gas case (both energy and entropy) you get numerical artifacts but that could just be the advection scheme. Quick test would be to see if increasing the resolution reduces those numerical artifacts.

But in general, good advection scheme seems pretty important.

Just skimmed through the changes but I won't review yet as it's a WIP. If there's a bug with entropy hopefully we'll find it during review or pair programming.

> 1. a more robust approach to tracking which model tracers are the thermodynamic variable and the densities (right now the code assumes that they're at certain indices of model.tracers)

Hmmm, yeah this might warrant us taking a slightly different approach than for incompressible models. I think a big benefit of having them be part of `model.tracers` is that they can be processed and time-stepped together.

One solution could be to define `model.thermodynamic_variables` and `model.densities` to be a named tuple of pointers to specific tracers in `model.tracers`. So we can treat them all similarly when calculating right hand sides or time stepping, but can pass in just `model.thermodynamic_variables` when needed, for example in a pressure calculation or microphysics scheme.

> 2. a more streamlined way to include diagnostic fields in operators. #59 would address this.

True. Maybe `model.tracers` can hold the prognostic fields while properties like `model.thermodynamic_variables` and `model.velocities` can hold lazy primitive fields.

> 3. some way to enforce boundary conditions on diagnostic fields (e.g. pressure, diffusive fluxes). Right now this can be done indirectly by setting boundary conditions on prognostic fields, but having a more direct way to apply them would simplify the code (and let us avoid hacks like the one in `diffusive_pressure_flux_z` in `compressible_operators.jl`, which is currently there because I couldn't figure out any other way to ensure the flux was zero at the top and bottom boundaries). #59 could also address this.

Ah sorry yeah the boundary conditions in `master` are still hacked in as I was hoping to include each field's boundary conditions in the `Field` struct (https://github.com/climate-machine/Oceananigans.jl/issues/606).

But yeah we definitely want to avoid hard-coding in boundary conditions like that!

Hmmm, this one seems like it could be a bit tricky if we really need boundary conditions and halo filling on diagnostic fields. Filling halos on the fly or on demand for lazy computations could be expensive.

It would be nice if we can get away with just imposing boundary conditions on prognostic fields so that lazy evaluations of the diagnostic variables will never have to worry about boundary conditions.

Hmmm, looking into `diffusive_pressure_flux_z`, I think it should be able to diagnose a zero pressure gradient if the thermodynamic variable has no-flux boundary condition (zero gradient or no-flux at the boundary), which should produce p/ρ = constant at the boundary. Then `∂zᵃᵃᶠ(i, j, k, grid, p_over_ρ_diag, tvar, g, Ũ, ρ, ρ̃, C̃) = 0`. But that must have not worked as you had to hard code in the no-flux boundary conditions. Looks like halo regions are filled correctly during time stepping too.

Worse case even if we had to "fill in halo regions" for lazy diagnostic fields I think we can do it generally and there will be a performance hit but it should be rather negligible.

> It also might be worth adding some regression tests before we start working on any of the above so that we have a way of making sure we're not changing model behavior (apart from fixes to any bugs we find) while refactoring.

True. I guess we don't have easy output writers built in yet (#38) but should be easy to output/load a few fields for the purposes of regression testing.

Been thinking of moving diagnostics and output writers out of the model and into a `Simulation` type (https://github.com/climate-machine/Oceananigans.jl/issues/447) so I haven't added an `output_writers` property field to `CompressibleModel` yet.

> @ali-ramadhan, let me know if you're interesting in working on any of these additions. (Might be worth doing some pair programming so we make sure we're both happy with the resulting code.)

Pair programming could be a good idea, especially to settle on design choices.

I'll try to push through a couple of upstream issues: https://github.com/climate-machine/Oceananigans.jl/issues/606 so it'll be much easier to add boundary conditions on all fields here, and https://github.com/climate-machine/Oceananigans.jl/issues/447 so we can start using diagnostics and output writers (and get rid of the time stepping loop).

But maybe more importantly, I can work on adding lazy fields (https://github.com/thabbott/JULES.jl/issues/59) which seem like they might be a much needed abstraction for a `CompressibleModel`.

**Comment by ali-ramadhan** [comment]
> Also want to note that this branch has or will have changes that address

I think if you include a list like
```
Resolves #49 
Resolves #52 
...
```
(but without the code block) in your original comment then those issues will be automatically closed when this PR is merged.

**Comment by thabbott** [comment]
> Even with the single gas case (both energy and entropy) you get numerical artifacts but that could just be the advection scheme. Quick test would be to see if increasing the resolution reduces those numerical artifacts.

I think the solutions in this branch might be more oscillatory than `master` in part because diffusion is less strong---`master` has κ = 0.5 m^2/s, but with a bug in the diffusion operators that makes this equivalent to κ = 500 m^2/s in this branch, whereas the videos I posted use κ = 75 m^2/s. I'm also using half the spatial resolution. So we could make the verification experiments look nicer pretty easily (but having better advection operators eventually would be good too).

> One solution could be to define model.thermodynamic_variables and model.densities to be a named tuple of pointers to specific tracers in model.tracers. So we can treat them all similarly when calculating right hand sides or time stepping, but can pass in just model.thermodynamic_variables when needed, for example in a pressure calculation or microphysics scheme.

Something like this seems good to me---I agree that keeping the thermodynamic variable and densities in the list of tracers is convenient, and this would give a straightforward and relatively low-cost way to access them when we need them individually.

> True. Maybe model.tracers can hold the prognostic fields while properties like model.thermodynamic_variables and model.velocities can hold lazy primitive fields.

It might make sense to store all the lazy diagnostic fields in another struct called something like `model.diagnostic_variables` so that we clearly distinguish them from variables that get stepped forward in time. But we can think more about the best way to organize things.

> Hmmm, looking into diffusive_pressure_flux_z, I think it should be able to diagnose a zero pressure gradient if the thermodynamic variable has no-flux boundary condition (zero gradient or no-flux at the boundary), which should produce p/ρ = constant at the boundary. Then ∂zᵃᵃᶠ(i, j, k, grid, p_over_ρ_diag, tvar, g, Ũ, ρ, ρ̃, C̃) = 0. But that must have not worked as you had to hard code in the no-flux boundary conditions. Looks like halo regions are filled correctly during time stepping too.

The problem comes from the fact that energy includes kinetic energy and halos for the vertical velocity field aren't filled the same way as other variables at the top and bottom boundaries. So even though the energy gradient is zero at boundaries the temperature and pressure gradients aren't. Calculating diffusive fluxes using lazy field with its own boundary condition might let us do something like
```julia
struct LazyGradient{B}
    scalar :: Field
    bc :: B
end

getindex(A::LazyGradient, inds...) = gradient(i, j, k, A.scalar.grid, A.scalar, A.bc)

function gradient(i, j, k, grid, scalar, bc::AllPeriodic)
   xcomp = ∂x(i, j, k, grid, scalar)
   ycomp = ∂y(i, j, k, grid, scalar)
   zcomp = ∂z(i, j, k, grid, scalar)
   return (xcomp, ycomp, zcomp)
end

function gradient(i, j, k, grid, scalar, bc::NoGradientZ)
   xcomp = ∂x(i, j, k, grid, scalar)
   ycomp = ∂y(i, j, k, grid, scalar)
   zcomp = (k == 1 || k == grid.Nz) ? 0.0 : ∂z(i, j, k, grid, scalar)
   return (xcomp, ycomp, zcomp)
end
```
This doesn't require extra halo filling but also handles the case where halo filling doesn't do what we'd like it to.

> I'll try to push through a couple of upstream issues: climate-machine/Oceananigans.jl#606 so it'll be much easier to add boundary conditions on all fields here, and climate-machine/Oceananigans.jl#447 so we can start using diagnostics and output writers (and get rid of the time stepping loop).
> 
> But maybe more importantly, I can work on adding lazy fields (#59) which seem like they might be a much needed abstraction for a CompressibleModel.

Sounds good to me!

**Comment by ali-ramadhan** [comment]
Of course it took longer than expected but I've made some changes to Oceananigans.jl that will benefit JULES so I'll update JULES to use the latest version and start with building up some lazy fields.

A quick summary:
1. Grids now have a topology which help inform boundary conditions (https://github.com/climate-machine/Oceananigans.jl/pull/614, https://github.com/climate-machine/Oceananigans.jl/pull/620)
2. `time_step!` now takes a single time step. A high-level `Simulation` abstraction handles time stepping, diagnostics, and output writing (https://github.com/climate-machine/Oceananigans.jl/pull/621).
3. Oceananigans.jl now implements an `IncompressibleModel` so there's room for a `CompressibleModel` (https://github.com/climate-machine/Oceananigans.jl/pull/626).
4. Boundary conditions are now a field property so JULES can readily support arbitrary boundary conditions (https://github.com/climate-machine/Oceananigans.jl/pull/631).

**Comment by ali-ramadhan** [comment]
I updated the time stepping a bit after the model reorganization.

I also updated the tests and noticed some out of bounds errors that probably weren't caught since they happen inside `@inbounds` blocks. Tests are nice like that as they force bounds checking.

How should potential energy and temperature be computed in the halo regions? Right now we have `Φ = gravity * grid.zC[k]` so we need to make a choice about `zC[0]` and `zC[Nz+1]` or about `Φ[0]` and `Φ[Nz+1]`.

Right now I'm just doing
```julia
k′ = k
k < 1 && (k′ = 1)
k > grid.Nz && (k′ = Nz)
Φ = gravity * grid.zC[k′]
```
which is probably not what we want but is probably better than silently accessing ranges out of bounds.

Updated and ran the 3-gas dry rising thermal bubble with energy verification and movie still looks good so looks like I didn't break things too much.

**Comment by ali-ramadhan** [comment]
Hmmm, I think something we changed led to a performance regression and lots of allocations (model should ~10x faster I think):
```
 ──────────────────────────────────────────────────────────────────────────────────
    Static atmosphere benchmarks           Time                   Allocations      
                                   ──────────────────────   ───────────────────────
         Tot / % measured:              49.3s / 6.85%           15.5GiB / 6.87%    

 Section                   ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────────────────────
 32×32×32 [CPU, Float64]       10    3.38s   100%   338ms   1.06GiB  100%    109MiB
 ──────────────────────────────────────────────────────────────────────────────────
```

Probably would be hard to find the culprit. We think it was working well in commit https://github.com/thabbott/JULES.jl/pull/60/commits/6327e2f720c733b91e5d3034a9c5d6a16a83bf18

**Comment by thabbott** [comment]
Good catch with the out-of-bounds accesses! We want boundary conditions on Φ to match boundary conditions on energy, so what you're doing is correct for no-flux top and bottom boundaries, but probably not something we want to keep hard-coded into the geopotential calculation. We could always add a new lazy field for Φ that can hold its own boundary conditions....

I can take a shot at tracking down the source of the allocations if you'd like. (It'd be a good way to get re-acquainted with the code after the changes you made.)

**Comment by ali-ramadhan** [comment]
> I can take a shot at tracking down the source of the allocations if you'd like. (It'd be a good way to get re-acquainted with the code after the changes you made.)

That would be sweet. We can then add a performance regression test to ensure we don't slow down the model by mistake.

Then I can make some more substantial changes so JULES can use the boundary conditions, diagnostics, output writers, etc. from Oceananigans.

**Comment by ali-ramadhan** [comment]
Resolves #49
Resolves #52
Resolves #54
Resolves #55
Resolves #56
Resolves #57
Resolves #58
Resolves #59

**Pull request merged**
