### PR TITLE
Prototyping and testing a `CompressibleModel`

### PR DESCRIPTION
**Pull request by ali-ramadhan**

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Been trying to set up a simple thermal bubble test (along the lines of #24) but I think the initial conditions are incompatible with the base/reference state so the bubble just explodes really quickly.

But at least the code doesn't blow up!

sad_thermal_bubble

**Comment by ali-ramadhan** [comment]
Some suggestion by @thabbott and @natgeo-wong:

1. Change surface pressure to reference pressure.

2. Might make sense to merge buoyancy and base state. They're not independent.

3. Base state should not be `\theta` but S.

4. Actually do arbitrary tracers properly.

5. Just define functions for pressure instead of pressure gradients.

6. Less meta-programming, overly specific types until we have more features that actually use them.

7. Change `molar_mass_moist_air` to `molar_mass_water_vapor`.

8. Make sure it's all dry for now.

9. Change all the defaults to entropy `S`.

**Comment by ali-ramadhan** [comment]
Hmmm, time-stepping test is failing (without `@inbounds`). I wonder if calculating viscous fluxes for compressible models requires halos of size 2 for some reason or if I did something wrong...

```
  BoundsError: attempt to access 18×18×18 OffsetArray(::Array{Float64,3}, 0:17, 0:17, 0:17) with eltype Float64 with indices 0:17×0:17×0:17 at index [-1, 1, 1]
  Stacktrace:
   [1] throw_boundserror(::OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, ::Tuple{Int64,Int64,Int64}) at ./abstractarray.jl:538
   [2] checkbounds at ./abstractarray.jl:503 [inlined]
   [3] getindex at /home/travis/.julia/packages/OffsetArrays/vIbpP/src/OffsetArrays.jl:130 [inlined]
   [4] getindex at /home/travis/.julia/packages/Oceananigans/Y5eBR/src/fields.jl:101 [inlined]
   [5] ℑxᶠᵃᵃ at /home/travis/.julia/packages/Oceananigans/Y5eBR/src/Operators/interpolation_operators.jl:16 [inlined]
   [6] U_over_ρ at /home/travis/build/thabbott/JULES.jl/src/Operators/compressible_operators.jl:90 [inlined]
   [7] δxᶜᵃᵃ at /home/travis/.julia/packages/Oceananigans/Y5eBR/src/Operators/difference_operators.jl:18 [inlined]
   [8] viscous_flux_ux at /home/travis/build/thabbott/JULES.jl/src/Operators/compressible_operators.jl:94 [inlined]
   [9] δxᶠᵃᵃ at /home/travis/.julia/packages/Oceananigans/Y5eBR/src/Operators/difference_operators.jl:19 [inlined]
   [10] div_μ∇u at /home/travis/build/thabbott/JULES.jl/src/Operators/compressible_operators.jl:107 [inlined]
   [11] FU at /home/travis/build/thabbott/JULES.jl/src/right_hand_sides.jl:13 [inlined]
   [12] compute_slow_forcings!(::NamedTuple{(:ρu, :ρv, :ρw, :Θᵐ, :Qv, :Ql, :Qi),Tuple{Field{Oceananigans.Face,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Face,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Face,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}}, ::RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}, ::Nothing, ::NamedTuple{(:ρu, :ρv, :ρw),Tuple{Field{Oceananigans.Face,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Face,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Face,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}}, ::Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}, ::NamedTuple{(:Θᵐ, :Qv, :Ql, :Qi),NTuple{4,Field{Oceananigans.Cell,Oceananigans.Cell,Oceananigans.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}}, ::NamedTuple{(:u, :v, :w, :Θᵐ, :Qv, :Ql, :Qi),NTuple{7,typeof(Oceananigans.zeroforcing)}}, ::Float64, ::Nothing) at /home/travis/build/thabbott/JULES.jl/src/time_stepping_kernels.jl:7
```

**Comment by ali-ramadhan** [comment]
@thabbott Would you be okay with us merging this branch into master? It's getting quite long but I think I'm close to getting the nonlinear density current test working (not verified though!).

**Comment by thabbott** [comment]
Yes, that's fine with me! And you shouldn't need any more than 1 halo for
the viscous fluxes, but getting the interpolation and differencing right is
tricky...

**Pull request merged**
